image:
backoff_limit: 2000
resources:
  nnodes: 1
  nproc_per_node: 
  node_type:
  requests: {}
  limits: {}
tolerations: []
elastic_policy:
  rdzv_backend: c10d
  rdzv_port: 44000
  min_replicas: 1
  max_replicas: 1
pvc:
  - name: pv-fsx
    mount_path: /fsx
  - name: pv-efs
    mount_path: /efs
git:
  repo_url:
  branch:
  commit:
pre_script: []
post_script: []
train:
  env: []
  command: []
  args: []
