apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc-fsx
spec:
  containers:
  - name: attach-pvc-fsx
    image: ubuntu:latest
    command: ["/bin/bash"]
    securityContext:
      privileged: true
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 3600; done"]
    volumeMounts:
    - name:  fsx 
      mountPath: /fsx
  volumes:
  - name:  fsx
    persistentVolumeClaim:
      claimName: pv-fsx # k8s persistent-volume-claim name
