apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorpack-fsx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  resources:
    requests:
      storage: 1200Gi
  volumeName: tensorpack-fsx
