apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorpack-efs-gp-bursting 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc 
  resources:
    requests:
      storage: 100Gi
