apiVersion: v1
kind: Secret
metadata:
  name: dex-oidc-client
  namespace:  {{ .Values.dex.namespace }}
type: Opaque
stringData:
  OIDC_CLIENT_ID: {{ .Values.dex.oidc.client_id }}
  OIDC_CLIENT_SECRET: {{ .Values.dex.oidc.client_secret }}