apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: {{ .Values.dex.namespace }}
spec:
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    app: dex
  type: ClusterIP
