apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dex
  namespace: {{ .Values.dex.namespace }}
spec:
  gateways:
  - {{ .Values.ingress.namespace }}/{{ .Values.ingress.gateway }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /dex/
    route:
    - destination:
        host: dex.{{ .Values.dex.namespace }}.svc.cluster.local
        port:
          number: 5556
