---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-process-{{ .Release.Name }}
data:
  data-process.sh: |
    #!/bin/bash
   
    {{- if .Values.git.repo_url }}
    mkdir -p $HOME/tmp/{{ .Release.Name }}
    GIT_CLONE_DIR=$HOME/tmp/{{ .Release.Name }}/$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 16 | head -n 1)
    git clone {{ .Values.git.repo_url }} $GIT_CLONE_DIR
    cd $GIT_CLONE_DIR

    {{- if .Values.git.branch }}
    git checkout {{ .Values.git.branch }}
    {{- end }}

    {{- if .Values.git.commit }}
    git fetch origin {{ .Values.git.commit }}
    git reset --hard {{ .Values.git.commit }}
    {{- end }}
    
    {{- end }}
    
    {{- range .Values.pre_script }}
    {{ . }}
    {{- end }}
    
    {{- range .Values.process.command }}
    {{ . }} \
    {{- end }}
    {{- range .Values.process.args }}
    {{ . }} \
    {{- end }}
    && echo "Processing script done"

    {{- range .Values.post_script }}
    {{ . }}
    {{- end }}

    {{- if .Values.git.repo_url }}
    cd $HOME
    rm -rf $GIT_CLONE_DIR
    {{- end }}

---
apiVersion: v1
kind: Pod
metadata:
  name: data-process-{{ .Release.Name }}
  annotations:
    karpenter.sh/do-not-disrupt: "true"
    sidecar.istio.io/inject: 'false'
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      defaultMode: 420
      items:
      - key: data-process.sh
        mode: 365
        path: data-process.sh
      name: data-process-{{ .Release.Name }}
  {{- $pv_index := 1 }}
  {{- range $pv := .Values.pvc }}
  - name: pv-{{ $pv_index }}
    persistentVolumeClaim:
      claimName: {{ $pv.name }}
  {{- $pv_index = add $pv_index 1 }}
  {{- end }}
  containers:
  - name: data-process
    command:
    -  sh 
    - /etc/config/data-process.sh
    image: {{ .Values.image }}
    volumeMounts:
    - mountPath: /etc/config
      name: config
    {{- $pv_index := 1 }}
    {{- range $pv := .Values.pvc }}
    - mountPath: {{ $pv.mount_path }}
      name: pv-{{ $pv_index }}
    {{- $pv_index = add $pv_index 1 }}
    {{- end }}
    resources:
      requests:
      {{- range $k, $v := .Values.resources.requests }}
        {{ $k }}: {{ $v }}
      {{- end }}
      limits:
      {{- range $k, $v := .Values.resources.limits }}
        {{ $k }}: {{ $v }}
      {{- end }}
