apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-efs
  namespace:  {{ .Values.user.profile }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: {{ .Values.user.profile }}-pv-efs
  resources:
    requests:
      storage: 100Gi