image:
pvc:
  - name: pv-fsx
    mount_path: /fsx
  - name: pv-efs
    mount_path: /efs
git:
  repo_url:
  branch:
  commit:
pre_script: []
post_script: []
process:
  env: []
  command: []
  args: []
resources:
  requests: {}
  limits: {}