image:
pvc:
  name: pv-fsx
  mount_path: /fsx
git:
  repo_url:
  branch:
  commit:
pre_script: []
post_script: []
process:
  command: []
  args: []
resources:
  requests:
    cpu: "1000m"
    memory: "384Mi"
  limits:
    cpu: "4000m"
    memory: "8192Mi"