apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc
spec:
  containers:
  - name: attach-pvc
    image: ubuntu:latest
    command: ["/bin/bash"]
    securityContext:
      privileged: true
    args: ["-c", "trap : TERM INT; sleep infinity & wait"]
    volumeMounts:
    - name:  efs 
      mountPath: /efs
    - name:  fsx 
      mountPath: /fsx
  volumes:
  - name:  efs
    persistentVolumeClaim:
      claimName: pv-efs # k8s persistent-volume-claim name
  - name:  fsx
    persistentVolumeClaim:
      claimName: pv-fsx # k8s persistent-volume-claim name
