apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-fsx
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  resources:
    requests:
      storage: 1200Gi
  volumeName: pv-fsx