apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: external-auth
  namespace: {{ .Values.ingress.namespace }} 
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        notPaths: ["/dex/*", "/authservice/logout"]  