apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fsx
spec:
  capacity:
    storage: 1200Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: <fsx-file-system-id>
    volumeAttributes:
      dnsname: <fsx-file-system-id>.fsx.<aws-region>.amazonaws.com
      mountname: <fsx-mount-name>
