---
apiVersion: v1
kind: ConfigMap
metadata:
  name: replicate-data 
data:
  replicate-data.sh: |
    aws s3 cp --recursive s3://$S3_BUCKET/$S3_PREFIX /ebs
    while true; do echo $(date -u) >> /root/date.txt; sleep 3600; done
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: replicate-data 
spec:
  selector:
    matchLabels:
      name: replicate-data 
  template:
    metadata:
      labels:
        name: replicate-data 
    spec:
      restartPolicy: Always
      volumes:
      - name: ebs
        hostPath:
           path: /ebs
           type: DirectoryOrCreate
      - name: config
        configMap:
          defaultMode: 420
          items:
          - key: replicate-data.sh
            mode: 365
            path: replicate-data.sh
          name: replicate-data 
      containers:
      - name: replicate-data 
        env:
        - name: S3_BUCKET
          value: my-bucket 
        - name: S3_PREFIX
          value: my-bucket-prefix 
        command:
        -  sh 
        - /etc/config/replicate-data.sh
        image: # use image with aws cli support  
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/config
          name: config
        - mountPath: /ebs
          name: ebs
