---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.mpioperator.name }}
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.mpioperator.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Values.mpioperator.name }}
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.mpioperator.name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - mpijobs/finalizers
  - mpijobs/status
  verbs:
  - '*'
- apiGroups:
  - scheduling.incubator.k8s.io
  - scheduling.sigs.dev
  resources:
  - queues
  - podgroups
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.mpioperator.name }}
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.mpioperator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.mpioperator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.mpioperator.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.mpioperator.name }}
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Values.mpioperator.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mpioperator.name }}
      app.kubernetes.io/component: mpijob
      app.kubernetes.io/name: {{ .Values.mpioperator.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ .Values.mpioperator.name }}
        app.kubernetes.io/component: mpijob
        app.kubernetes.io/name: {{ .Values.mpioperator.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - args:
        - -alsologtostderr
        - --lock-namespace
        - {{ .Values.global.namespace }}
        image: {{ .Values.mpioperator.image }}
        imagePullPolicy: {{ .Values.mpioperator.pullpolicy }} 
        name: {{ .Values.mpioperator.name }}
      serviceAccountName: {{ .Values.mpioperator.name }}