apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyter.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.jupyter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.jupyter.port }} 
    targetPort:  {{ .Values.jupyter.target_port }}
  selector:
    app: {{ .Values.jupyter.name }}
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.jupyter.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.jupyter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.jupyter.name }}
    spec:
      volumes:
      - name: {{ .Values.global.shared_fs }} 
        persistentVolumeClaim:
            claimName: {{ .Values.global.shared_pvc }}
      containers:
      - name:  {{ .Values.jupyter.name }}
        command:
        - jupyter
        args:
        - lab 
        - --allow-root
        - --no-browser 
        - --ip=0.0.0.0 
        - --certfile=/labs-cert.pem 
        - --keyfile=/labs-key.key
        image: {{ .Values.jupyter.image }} 
        imagePullPolicy: {{ .Values.jupyter.image_pull_policy }}
        ports:
        - containerPort:  {{ .Values.jupyter.target_port }}
        volumeMounts:
        - mountPath: /{{ .Values.global.shared_fs }}
          name: {{ .Values.global.shared_fs }}
