---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyter.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.jupyter.port }} 
    targetPort:  {{ .Values.jupyter.target_port }}
  selector:
    app: {{ .Values.jupyter.name }}
  type: LoadBalancer
  loadBalancerSourceRanges:
  - {{ .Values.global.source_cidr }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jupyter.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.jupyter.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
     app: {{ .Values.jupyter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.jupyter.name }}
    spec:
      volumes:
      - name: {{ .Values.global.shared_fs }} 
        persistentVolumeClaim:
            claimName: {{ .Values.global.shared_pvc }}
      containers:
      - name:  {{ .Values.jupyter.name }}
        command:
        - jupyter
        args:
        - lab 
        - --allow-root
        - --no-browser 
        - --ip=0.0.0.0 
        - --port={{ .Values.jupyter.target_port }} 
        - --certfile=/labs-cert.pem 
        - --keyfile=/labs-key.key
        - "--ServerApp.ssl_options={'ssl_version': 5}"
        image: {{ .Values.jupyter.image }} 
        imagePullPolicy: {{ .Values.jupyter.image_pull_policy }}
        ports:
        - containerPort:  {{ .Values.jupyter.target_port }}
        volumeMounts:
        - mountPath: /{{ .Values.global.shared_fs }}
          name: {{ .Values.global.shared_fs }}
        resources:
          limits:
            nvidia.com/gpu: 1
